// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwvgx1PCi1yAGGM0-ur-V-oA-_caVVcc',
    appId: '1:414187782486:web:4545728dea2be72ed696f7',
    messagingSenderId: '414187782486',
    projectId: 'agrobuddy-fa6bd',
    authDomain: 'agrobuddy-fa6bd.firebaseapp.com',
    storageBucket: 'agrobuddy-fa6bd.firebasestorage.app',
    measurementId: 'G-DSWRESJEN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1mbrbo7Onel62qF_TWMZgSlhCt9eVhCo',
    appId: '1:414187782486:android:743fccb21b8aa64cd696f7',
    messagingSenderId: '414187782486',
    projectId: 'agrobuddy-fa6bd',
    storageBucket: 'agrobuddy-fa6bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6IEiZ6OkPAe02zHlq95R6auBQlLeHRHs',
    appId: '1:414187782486:ios:64a6bf54cce6e815d696f7',
    messagingSenderId: '414187782486',
    projectId: 'agrobuddy-fa6bd',
    storageBucket: 'agrobuddy-fa6bd.firebasestorage.app',
    iosBundleId: 'com.example.tickify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6IEiZ6OkPAe02zHlq95R6auBQlLeHRHs',
    appId: '1:414187782486:ios:64a6bf54cce6e815d696f7',
    messagingSenderId: '414187782486',
    projectId: 'agrobuddy-fa6bd',
    storageBucket: 'agrobuddy-fa6bd.firebasestorage.app',
    iosBundleId: 'com.example.tickify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkwvgx1PCi1yAGGM0-ur-V-oA-_caVVcc',
    appId: '1:414187782486:web:b6bed43cca31ff88d696f7',
    messagingSenderId: '414187782486',
    projectId: 'agrobuddy-fa6bd',
    authDomain: 'agrobuddy-fa6bd.firebaseapp.com',
    storageBucket: 'agrobuddy-fa6bd.firebasestorage.app',
    measurementId: 'G-BQ65G3P78L',
  );

}